// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

type SupabaseLike = ReturnType<typeof createClient<Database>>;

function createFallbackClient(): SupabaseLike {
  const fallbackMethod = () => Promise.resolve({ data: null, error: null } as const);
  const fallbackChannel = () => ({
    on: () => fallbackChannel(),
    subscribe: () => Promise.resolve(),
    unsubscribe: () => Promise.resolve(),
  });

  return new Proxy({} as SupabaseLike, {
    get(_, prop) {
      if (prop === "from") return () => ({
        select: fallbackMethod,
        insert: fallbackMethod,
        update: fallbackMethod,
        upsert: fallbackMethod,
        delete: fallbackMethod,
        eq: () => ({ select: fallbackMethod, update: fallbackMethod, delete: fallbackMethod, order: () => ({ select: fallbackMethod }) }),
        order: () => ({ select: fallbackMethod }),
        maybeSingle: fallbackMethod,
        single: fallbackMethod,
        or: () => ({ select: fallbackMethod, order: () => ({ select: fallbackMethod }) }),
      });
      if (prop === "channel") return fallbackChannel;
      if (prop === "rpc") return fallbackMethod;
      if (prop === "auth") return {
        getClaims: fallbackMethod,
      };
      return undefined;
    },
  });
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn(
      "Supabase env vars are missing. Using a safe fallback client so the app can render without crashing.",
    );
    return createFallbackClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy(
  {} as ReturnType<typeof createSupabaseClient>,
  {
    get(_, prop, receiver) {
      if (!_supabase) _supabase = createSupabaseClient();
      return Reflect.get(_supabase, prop, receiver);
    },
  },
);
